### ISSUE TITLE
adding a long hardlink without _fs APIs

### ISSUE THREAD

**Issue by the8472** [alexcrichton/tar-rs#192]
Similar to #108, the internal helper method for [appending long links](https://github.com/alexcrichton/tar-rs/blob/7473c27372a8adaf946e61836eeabf36ed2e25dc/src/builder.rs#L467-L479) is only accessible through APIs that attempt to access the filesystem.

It would be great if it were possible to pass a header (with symlink or hardlink `entry_type`) and a `name` + `link_name` as `Path` and have the builder insert the necessary long-name headers. I.e. an equivalent to `append_data`

Maybe some general intermediate-level API is missing for adding headers and data separately to orthogonalize the construction of complicated headers that must be written in several parts (long name, long links, sparse header) and their associated data chunks. A single function taking several enums to cover all those combinations might work too.

**Comment by cgwalters** [comment]
I'm hitting this in https://github.com/ostreedev/ostree-rs-ext/issues/162

I'm willing to work on a PR here.  But reading the code, one thing that strikes me as somewhat odd is that we have this "base interface" in `tar::Header` and APIs to "cast" it to e.g. a `GnuHeader`.

But why do we not directly expose all the API methods like `set_link_name()` on `GnuHeader`?  In my case, I know I am writing a GNU-formatted tar archive.  I always want that behavior.

It seems weird to me how many of the `Header` methods do things like:

```
    fn _set_path(&mut self, path: &Path) -> io::Result<()> {
        if let Some(ustar) = self.as_ustar_mut() {
            return ustar.set_path(path);
        }
        ...
    // Or base case here
```

The inverse problem here is that the `append_data()` behavior of trying the base case but silently "upgrading" to GNU may not be what some people want - they may want to fail instead of writing a GNU entry.  I admit this use case is probably obscure, but to rephrase I think we should be consistent in our interface - the format of an archive *as a whole* is either GNU or PAX or base, etc.

**Comment by cgwalters** [comment]
PR in https://github.com/alexcrichton/tar-rs/pull/273

**Comment by cgwalters** [comment]
(Regarding my confusion around `Header` above, the reason we need a special case `append_data()` is internally it's represented as *two* tar entries, so we need to handle it via `Builder`)
