### ISSUE TITLE
Archive::files returns Ok on bad input

### ISSUE THREAD

**Issue by nixpulvis** [alexcrichton/tar-rs#30]
I could be misunderstanding the `Err` cases for `Archive::files`, but I would expect the following to work differently. More details in comments of the code.

```rust
extern crate tar;

use std::io::prelude::*;
use std::fs::File;
use tar::Archive;

fn main() {
    // Cargo.lock, obviously not a tar archive.
    let file = File::open("Cargo.lock").unwrap();
    let archive = Archive::new(file);

    // I'd expect this to panic.
    let files = archive.files().unwrap();
    // This shouldn't work.
    println!("{}", files.count());

    // I'd expect this to panic, again.
    let mut files = archive.files().unwrap();
    let f = files.next();
    let mut buf = [];
    // Errors here with 'invalid tar archive'.
    f.unwrap().unwrap().read(&mut buf);
}

```

**Comment by alexcrichton** [comment]
This library currently attempts to minimize the amount of I/O performed, so the failure mode of `archive.files()` is the initial `seek` that's performed, and then other errors (e.g. about format) are delayed until the iteration. That's why when the first item is requested an error is yielded because of a bad format.

It could be possible to actually make `files()` infallible to emphasize that it doesn't validate any internal data, however, which may make this more clear.

**Comment by nixpulvis** [comment]
I'm still relatively new to actually programming things in Rust, so many of the conventions around when and when not to use `Result` and `Option`s are still sinking in for me. Generally speaking I think it makes the most sense to only require one check for TAR archive format. This library already requires a lot of unwrapping and error checking.

**Comment by alexcrichton** [comment]
> Generally speaking I think it makes the most sense to only require one check for TAR archive format. This library already requires a lot of unwrapping and error checking.

I certainly agree on principle, but there's a reason this library returns so many `Result`s! Many operations can go wrong when processing a file which is assumed to be in a particular format, and I'd recommend using `try!` instead of unwrap wherever possible.

I also don't think this library wants to validate the entire archive up front as it would require reading the entire archive instead of being able to skip around and avoid reading large portions from disk.

**Comment by nixpulvis** [comment]
Totally agree about avoiding reading until needed. I think this could really just be solved by explaining in the documentation what exactly each `Result` or `Option` checked. My assumption at first was that if `Archive::files` was `Ok` then the TAR was well formatted.

**Comment by alexcrichton** [comment]
Oh yeah the documentation could certainly be improved throughout!

**Comment by nixpulvis** [comment]
Closing because it's not really an issue per say.
