### ISSUE TITLE
Append does not require a mut reference

### ISSUE THREAD

**Issue by aidanhs** [alexcrichton/tar-rs#31]
I noticed this by accident and found it a bit confusing. Although it's perfectly safe (courtesy of the refcell), it is a little surprising that by passing an immutable reference to a function, you could end up with the archive mutated!

Is this a deliberate design decision, and is exactly why RefCell is used?

**Comment by alexcrichton** [comment]
Yeah this is currently intentional because of the usage of `RefCell`. That's in turn used because of the `.iter()` method which may require a bunch of seeking while iterating, and it's also somewhat useful later on for other operations. This is basically an instance of "interior mutability" instead of exposing it at the API layer.

**Comment by aidanhs** [comment]
Thanks for explaining, that makes sense.
(also, sorry for raising as an issue - I figured it might be helpful for future searchers)

**Comment by alexcrichton** [comment]
Ah no worries, thanks for the report regardless!
