### ISSUE TITLE
Expose the entry type in Header

### ISSUE THREAD

**Issue by mbrt** [alexcrichton/tar-rs#39]
The entry type is now parsed from `Header`, but the information is kept private. The raw information is available trough the public field `link`, so the information is already there. I think it's useful to:
* promote `EntryType` to be public;
* add a `entry_type` getter in `Header`.

**Comment by alexcrichton** [comment]
This seems pretty plausible to me, yeah, although I'd prefer to tweak the API if this were the case:

* The returned value should be an opaque struct instead of an `enum`
* Variants should be moved to `is_foo` accessors.
* There'd be a method to extract the raw underlying byte.

Other than that though I'm game!

**Comment by aidanhs** [comment]
> The returned value should be an opaque struct instead of an enum

Out of curiosity, why have you gone this route? This means match can't check for exhaustiveness any more.

**Comment by aidanhs** [comment]
In particular, users of this library now won't be informed automatically if I add support for posix extended headers and gnu extensions - they'll need to read the library documentation, rather than the compiler informing them on library upgrade.
(of course, it's not failsafe but I'm not sure what advantage the struct has)

**Comment by alexcrichton** [comment]
Ah I just opted for an opaque struct for help in terms of backwards compatibility. It looks like there are a number of standards for the tar format and they all tend to add various new types that are recognized, so I wouldn't be confident that we could exhaustively enumerate the set of types, so in that sense I'm not sure there *can* be an exhaustive match. It is true, though, that this makes it a little harder to "support everything by default" as it's easy to forget a case or two.

On the flip side, however, it provides a graceful way to handle unknown file types (e.g. weird bytes) and to get/create via raw bytes as well.

**Comment by aidanhs** [comment]
Would something like
```
enum EntryType {
    Regular,
    Link,
[...]
    Unknown(u8),
}
```
allow exhaustive matching and handle strange bytes?

Yes, the one thing I do like about the struct is that the byte is stored with it, rather than having to do a lookup.

**Comment by alexcrichton** [comment]
In theory, yeah, but it doesn't allow backwards-compatible expansion to new `EntryType` instances in the future (as it'd break exhaustive matches)

**Comment by mbrt** [comment]
@alexcrichton I think you are right in this particular case. However I'd like to know what's the choice made in the standard library for similar cases. For example [`std::fs::Metadata`](http://doc.rust-lang.org/std/fs/struct.Metadata.html) made it the same. Is it standard to avoid enumerations when extensions are expected to come in future? Because it lessen the scope for enums very much.

Sorry for the - more or less - OT question.

**Comment by alexcrichton** [comment]
@mbrt yeah in general enums are not intended for extensible types. They're great for private implementation details but in terms of an exported interface you can only reliably use them if you're either 100% sure that you've covered all possible future variants *or* you're fine making breaking changes to the enum type.

**Comment by aidanhs** [comment]
@alexcrichton thanks for taking the time to answer questions about design decisions like this, it's much appreciated and very illuminating.

**Comment by alexcrichton** [comment]
No problem! Always a fan of talking about APIs in Rust :)

**Comment by dbrgn** [comment]
A small comment about this discussion:

> In theory, yeah, but it doesn't allow backwards-compatible expansion to new EntryType instances in the future (as it'd break exhaustive matches)

If people want to match exhaustively, they probably do want to get a compilation error once new types are added.

If they only care about a subset of the possible types, they should probably use `match { ..., _ => default_handling() }` in the first place. Then adding new types does not affect them.

I'd also argue for using an `enum` instead of an opaque struct, it's simply much more ergonomic to use :)

**Comment by aidanhs** [comment]
Per the discussion, I think I'd find an enum vaguely useful (but don't have strong feelings on it). Could it be marked as unstable to clarify that it's not forwards compatible (and never will be)?

**Comment by alexcrichton** [comment]
Unfortunately instability is not available to non-libstd crates (e.g. it's a nightly feature), and @dbrgn the problem is that when adding a new variant a new major version bump of this library would need to be made, which unfortunately isn't worth it.

**Comment by dbrgn** [comment]
> and @dbrgn the problem is that when adding a new variant a new major version bump of this library would need to be made, which unfortunately isn't worth it.

I'm not saying you need a major version update to do this change, but maybe you could include it in your next major update :)

**Comment by dbrgn** [comment]
Today I stumbled over a library that faced a similar situation: https://github.com/rust-lang-nursery/regex/blob/2065b416e93cb79d61133b8a9ae6b4d0cee075b6/regex-syntax/src/lib.rs#L717-L723
